name: CI/CD Pipeline for OWASP Juice Shop

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000
      defectdojo:
        image: defectdojo/defectdojo-django
        ports:
          - 8080:8080
        options: >
          --health-cmd="curl --fail http://localhost:8080/api/v2/" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
    

    steps:
      - name: Wait for Juice Shop to Start
        run: |
          echo "Waiting for Juice Shop to start..."
          sleep 60
          curl -v http://localhost:3000 | grep "OWASP Juice Shop"

      - name: Wait for DefectDojo to Start
        run: |
          echo "Waiting for DefectDojo to start..."
          for i in {1..30}; do
            curl -s http://localhost:8080/api/v2/ && break
            echo "Retrying in 10 seconds..."
            sleep 10
          done

  codeql-sast:
    name: Static Application Security Testing (SAST) with CodeQL
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/security"

      - name: Upload CodeQL Report to DefectDojo
        run: |
          curl -X POST "http://localhost:8080/api/v2/import-scan/" \
          -H "Authorization: Token 3c7e450aaf86ed7599812213e59f8f3a26ef0916" \
          -F scan_type="CodeQL" \
          -F file=@/home/runner/work/juiceshopdevesecops/results/javascript.sarif \
          -F product_name="OWASP Juice Shop" \
          -F engagement_name="CodeQL SAST"

  sca:
    name: Software Composition Analysis (SCA) with Dependency-Check
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Dependency-Check
        run: |
          ./dependency-check.sh \
          --project "Juice Shop" \
          --scan ./juice-shop \
          --format XML \
          --out reports
      - name: Upload Dependency-Check Report to DefectDojo
        run: |
          curl -X POST "http://localhost:8080/api/v2/import-scan/" \
          -H "Authorization: Token 3c7e450aaf86ed7599812213e59f8f3a26ef0916" \
          -F scan_type="Dependency Check" \
          -F file=@reports/dependency-check-report.xml \
          -F product_name="OWASP Juice Shop" \
          -F engagement_name="SCA"

  dast:
    name: Dynamic Application Security Testing (DAST) with OWASP ZAP
    needs: build-and-deploy
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
      - name: Wait for Juice Shop to Start
        run: |
          echo "Waiting for Juice Shop to start..."
          sleep 60
          curl -v http://localhost:3000 || exit 1

      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:3000'
          cmd_options: '-w report_md.md -r report_html.html -J report_json.json -a'

      - name: Upload ZAP Report to DefectDojo
        run: |
          curl -X POST "http://localhost:8080/api/v2/import-scan/" \
          -H "Authorization: Token 3c7e450aaf86ed7599812213e59f8f3a26ef0916" \
          -F scan_type="ZAP Scan" \
          -F file=@report_json.json \
          -F product_name="OWASP Juice Shop" \
          -F engagement_name="DAST"
