name: CI/CD Pipeline for OWASP Juice Shop

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
      - name: Wait for Juice Shop to Start
        run: |
          echo "Waiting for Juice Shop to start..."
          sleep 60
          curl -v http://localhost:3000 | grep "OWASP Juice Shop"

  dast:
    name: Dynamic Application Security Testing (DAST) with OWASP ZAP
    needs: build-and-deploy
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
      - name: Wait for Juice Shop to Start
        run: |
          echo "Waiting for Juice Shop to start..."
          sleep 60
          curl -v http://localhost:3000 || exit 1

      - name: Check Juice Shop Logs
        run: docker logs $(docker ps -q --filter ancestor=bkimminich/juice-shop)

      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://lo
