name: CI/CD Pipeline for OWASP Juice Shop

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Juice Shop Docker Image
        run: docker pull bkimminich/juice-shop

      - name: Run Juice Shop Docker Container
        run: docker run -d -p 3000:3000 bkimminich/juice-shop

      - name: Wait for Service to Start
        run: sleep 30

      - name: List Running Containers
        run: docker ps

      - name: Debug Health Check
        run: curl -v http://localhost:3000

      - name: Health Check
        run: curl -s http://localhost:3000 | grep "OWASP Juice Shop"

  codeql-sast:
    name: Static Application Security Testing (SAST) with CodeQL
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/security"
